config/routes.rb
Rails.application.routes.draw do
  resources :charities do
    resources :donations
  end
  root :to => "charities#index"
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  validates_presence_of :name, presence: :true

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  validates_presence_of :name, presence: :true

  def charge_card
    begin
      Stripe.api_key = "sk_test_htCgoOmkpccvOtvsgYCRDM6C"
      charge = Stripe::Charge.create(
        :amount => self.amount, # amount in cents, again
        :currency => "usd",
        :card => self.token,
        :description => self.user.email
      )
    rescue Stripe::CardError => e
      # The card has been declined
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

  def index
    @charities = Charity.all
  end

  def new
    @charity = Charity.new
  end

  def show
    @charity = Charity.find(params[:id])
  end

  def create
    @charity = Charity.new(charity_params)
    if @charity.save
      flash[:notice] = "charity created"
      redirect_to root_path
    else
      flash[:notice] = "Invalid charity"
      redirect_to new_charity_path
    end

  end

  def edit
    @charity = Charity.find(params[:id])
  end

  def update
    @charity = Charity.find(params[:id])
    if @charity.update(charity_params)
      flash[:notice] = "Charity updated"
    else
      flash[:notice]= "update failed"
      redirect_to edit_charity_path(@charity)
    end
  end

  def destroy
    @charity = Charity.find(params[:id])
    @charity.destroy
    flash[:notice] = "Your charity has been deleted"
    redirect_to root_path
  end

  private

  def charity_params
    params.require(:charity).permit(:name, :description)
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def index
    @dontaions = Donation.all
  end

  def new
    @donation = Donation.new
    @charity = Charity.find(params[:charity_id])
  end

  def show
    @donation = Donation.find(params[:id])
  end

  def create
    @charity = Charity.find(params[:charity_id])
    @donation = Donation.new({:charity_id => @charity.id, :token => params[:token]})
    if @donation.save
      card = Stripe.card.createToken
      card.charge_card

      flash[:notice] = "donation created"
      redirect_to root_path
    else
      flash[:notice] = "Invalid donation"
      redirect_to charity_path(@charity)
    end

  end

  def edit
    @donation = Donation.find(params[:id])
  end

  def update
    @donation = Donation.find(params[:id])
    if @donation.update(donation_params)
      flash[:notice] = "Donation updated"
    else
      flash[:notice]= "update failed"
      redirect_to edit_donation_path(@donation)
    end
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy
    flash[:notice] = "Your donation has been deleted"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charities/_form.html.erb
<%= form_for @charity do |f| %>
<div class="form-group">
  <%= f.label "Name" %>
  <%= f.text_field :name, class: "form-control"%>
</div>
<div class="form-group">
  <%= f.label "Description" %>
  <%= f.text_area :description, class: "form-control" %>
</div>
<%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/charities/index.html.erb
<h1>Charities</h1>

<% @charities.each do |charity| %>
<ul>
  <li><%= link_to charity.name, charity_path(charity) %></li>
</ul>
<% end %>



<%= link_to "New Charity", new_charity_path %>

app/views/charities/new.html.erb
<%= render 'form' %>

app/views/charities/show.html.erb
<h1><%= @charity.name %></h1>
<p><%= @charity.description %></p>
<%= link_to "Donate to #{@charity.name}", new_charity_donation_path(@charity) %>

app/views/donations/new.html.erb
<h1><%= @charity.name %></h1>

<form action="/charities/<%= @charity.id %>/donations" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nonprofit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_6pRNASCoBOKtIshFeQd4XMUh');
  // ...
  </script>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
</head>
<body>

  <%= flash[:alert] %>
  <%= flash[:notice] %>

<%= yield %>

</body>
</html>